# Generated by Django 2.0.2 on 2018-02-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50000)),
                ('spotifylink', models.CharField(max_length=1000)),
                ('soundcloudlink', models.CharField(max_length=1000)),
                ('bandcamplink', models.CharField(max_length=1000)),
                ('applemusiclink', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ineedaname', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ineedaname', max_length=50)),
                ('published_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('typevideotrack', models.CharField(max_length=50)),
                ('releasedate', models.DateField()),
                ('link', models.CharField(max_length=1000)),
                ('artists', models.ManyToManyField(to='main.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='carousel',
            name='images',
            field=models.ManyToManyField(to='main.Image'),
        ),
        migrations.AddField(
            model_name='artist',
            name='releases',
            field=models.ManyToManyField(blank=True, to='main.Release'),
        ),
    ]
